import Lax619925.Series
import Lax619925.Prevariety
import Lax619925.Commutativity
import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.Algebra.Algebra.Basic

/-!
---
title: Hadamard automata and Hadamard-finite series
type: theorem
---
A series is *Hadamard-finite* if it lies in the Hadamard algebra generated by a
finite tuple of series that is closed under left derivatives (paper §5): the
Hadamard product is the pointwise product of the underlying functions, so the
Hadamard algebra is just the (pointwise) ring of series.  Equivalently (the
coincidence), it is recognised by a *Hadamard automaton* `(k, F, Δ)`: a
configuration space `ℚ[X_1, …, X_k]`, a final-weight functional `F`, and a
transition `Δ_a` that extends to an endomorphism of the configuration space.
The Hadamard-finite series form an effective prevariety, so equality and the
commutativity problem are decidable for them; the equality decision reduces to
ideal membership in the configuration polynomial ring (the open leaf).
-/

namespace Lax619925.Hadamard

open Lax619925.Series Lax619925.Prevariety Lax619925.Commutativity

/-- The Hadamard product of two series, defined element-wise:
    `(hadamard f g) w = f w * g w`.  It is the pointwise product of the
    underlying functions, hence associative, commutative, and distributive over
    addition, with identity the constant-1 series. -/
def hadamard (α : Type*) (f g : Series α) : Series α := fun w => f w * g w

/-- The Hadamard-algebra evaluation of the polynomial `p` at the series `fs`:
    `hadamardEval fs p = Σ_m p m · ∏_i (fs i)^{m i}`, the interpretation of `p` in
    the (pointwise) ring of series, where the variable `X_i` is mapped to `fs i` and
    the multiplication is the Hadamard (pointwise) product. -/
def hadamardEval (α : Type*) (k : ℕ) (fs : Fin k → Series α) (p : MvPolynomial (Fin k) ℚ) :
    Series α :=
  fun w => p.support.sum fun m => p.coeff m * ∏ i : Fin k, (fs i) w ^ (m i)

/-- A series is *Hadamard-finite* (working definition, paper §5) if it is a Hadamard
    polynomial in a finite tuple of series `fs` that is closed under left
    derivatives: `f = p(fs)` for some polynomial `p`, and `leftDeriv a (fs i)` is
    again a Hadamard polynomial in `fs` for every letter `a` and index `i`.  Here
    `p(fs)` is the evaluation of `p` in the (pointwise) ring of series, i.e. the
    Hadamard algebra. -/
def IsHadamardFinite (α : Type*) (f : Series α) : Prop :=
  ∃ k : ℕ, ∃ fs : Fin k → Series α, ∃ p : MvPolynomial (Fin k) ℚ,
    f = hadamardEval α k fs p ∧
    ∀ a : α, ∀ i : Fin k, ∃ q : MvPolynomial (Fin k) ℚ,
      leftDeriv α a (fs i) = hadamardEval α k fs q

/-- A *Hadamard automaton* over `α`: a dimension `k ≥ 1` (the number of
    nonterminals `X_1, …, X_k`), a final-weight functional `F`, and a transition
    `Δ` assigning to each letter `a` and nonterminal `X_i` a polynomial `Δ a i` in
    the nonterminals.  The configuration space is the polynomial ring
    `ℚ[X_1, …, X_k] = MvPolynomial (Fin k) ℚ`. -/
structure HadamardAutomaton (α : Type*) where
  dim : ℕ
  hdim : 0 < dim
  F : Fin dim → ℚ
  Δ : α → Fin dim → MvPolynomial (Fin dim) ℚ

/-- The word extension of the transition: `Δ_w` is the endomorphism of the
    configuration space obtained by composing the letter endomorphisms
    `aeval (Δ a)` along the word, right-to-left.  `Δ_ε` is the identity and
    `Δ_{a·w} = Δ_w ∘ Δ_a`. -/
noncomputable def HadamardAutomaton.Mword {α : Type*} (A : HadamardAutomaton α) (w : List α) :
    MvPolynomial (Fin A.dim) ℚ → MvPolynomial (Fin A.dim) ℚ :=
  w.foldr (fun a φ => fun β => φ (MvPolynomial.aeval (A.Δ a) β)) id

/-- The series recognised by the automaton at a configuration `cfg`:
    `⟦A⟧_cfg (w) = F(Δ_w cfg)`, the final-weight functional applied to the
    configuration reached after reading `w`. -/
noncomputable def HadamardAutomaton.sem {α : Type*} (A : HadamardAutomaton α)
    (cfg : MvPolynomial (Fin A.dim) ℚ) : Series α :=
  fun w => MvPolynomial.eval (fun i => A.F i) (A.Mword w cfg)

/-- The series recognised by the automaton: the semantics at the initial
    configuration `X_0` (the first nonterminal). -/
noncomputable def HadamardAutomaton.recognised {α : Type*} (A : HadamardAutomaton α) :
    Series α :=
  A.sem (MvPolynomial.X (Fin.mk 0 A.hdim))

/-- A series is *Hadamard-recognisable* if it is recognised by some Hadamard automaton. -/
def IsHadamardRecognisable (α : Type*) (f : Series α) : Prop :=
  ∃ A : HadamardAutomaton α, A.recognised = f

/-- A series is Hadamard-finite if and only if it is Hadamard-recognisable
    (paper §5, the coincidence lemma). -/
axiom HadamardCoincidence (α : Type*) (f : Series α) :
  IsHadamardFinite α f ↔ IsHadamardRecognisable α f

/-- The class of Hadamard-finite series is closed under addition, scalar
    multiplication, the Hadamard product, and right derivatives (paper §5, the
    closure lemma).  These four parts hold over any alphabet. -/
axiom HadamardClosure (α : Type*) :
  (∀ (f g : Series α), IsHadamardFinite α f → IsHadamardFinite α g → IsHadamardFinite α (f + g)) ∧
  (∀ (c : ℚ) (f : Series α), IsHadamardFinite α f → IsHadamardFinite α (c • f)) ∧
  (∀ (f g : Series α), IsHadamardFinite α f → IsHadamardFinite α g → IsHadamardFinite α (hadamard α f g)) ∧
  (∀ (a : α) (f : Series α), IsHadamardFinite α f → IsHadamardFinite α (rightDeriv α a f))

/-- The class of Hadamard-finite series over a *finite* alphabet is closed under left
    anti-derivatives (paper §5): if `g` is a left anti-derivative of a tuple `f` of
    Hadamard-finite series, then `g` is Hadamard-finite.  The finiteness of the
    alphabet is essential — the witnessing generator tuple is extended by one series
    per letter, so it is finite only when the alphabet is. -/
axiom HadamardAntiDerivativeClosure (α : Type*) [Fintype α] :
  ∀ (g : Series α) (f : α → Series α), IsLeftAntiDerivative α g f →
      (∀ a, IsHadamardFinite α (f a)) → IsHadamardFinite α g

/-- The class of Hadamard-finite series is an effective prevariety over a finite
    alphabet (paper §5, theorem): there is an effective prevariety whose image is
    exactly the Hadamard-finite series, with presentations given by Hadamard
    automata. -/
axiom HadamardEffectivePrevariety (α : Type*) [Fintype α] :
  ∃ P : EffectivePrevariety α, ∀ f, IsHadamardFinite α f ↔ ∃ r : P.Rep, P.sem r = f

/-- The equality (zeroness) problem is decidable for Hadamard automata over a finite
    alphabet (paper §5): there is a procedure that, given a Hadamard automaton,
    decides whether the series it recognises is the zero series.  The decision
    reduces to ideal membership in the configuration polynomial ring, the open
    leaf. -/
axiom HadamardEqualityDecidable (α : Type*) [Fintype α] :
  ∃ d : HadamardAutomaton α → Bool, ∀ A, d A = true ↔ A.recognised = 0

/-- In particular, the commutativity problem is decidable for Hadamard-finite series
    over a finite alphabet (paper §5): there is a procedure that, given a Hadamard
    automaton, decides whether the series it recognises is commutative.  This is the
    meta-theorem applied to the effective prevariety of Hadamard-finite series. -/
axiom HadamardCommutativityDecidable (α : Type*) [Fintype α] :
  ∃ d : HadamardAutomaton α → Bool, ∀ A, d A = true ↔ IsCommutative α (A.recognised)

end Lax619925.Hadamard
