import Lax619925.IdealMembership
import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.Tactic

namespace Lax619925Proofs.IdealMembership

/--
---
conclusion: Lax619925.IdealMembership.IdealMembershipDecidable
---
Ideal membership in `MvPolynomial (Fin k) ℚ` is decidable in the propositional
sense: there is a `Bool`-valued function `dec` with `dec p = true` exactly
when `p` lies in the ideal generated by `gens`.  The proof is classical —
excluded middle supplies the characteristic function
`if p ∈ span ↑gens then true else false` — and not the constructive
Gröbner-basis decision procedure (Buchberger's algorithm), which mathlib does
not yet provide and which is out of scope for this submission.  This statement
is the propositional shadow of the paper's effective-decidability claim; the
three automaton equality theorems reduce to it via the ideal-chain argument.
-/
theorem IdealMembershipDecidable (k : ℕ) (gens : Finset (MvPolynomial (Fin k) ℚ)) :
  ∃ dec : MvPolynomial (Fin k) ℚ → Bool, ∀ p, dec p = true ↔ p ∈ Ideal.span ↑gens := by
  classical
  refine ⟨fun p => if p ∈ Ideal.span ↑gens then true else false, fun p => ?_⟩
  by_cases h : p ∈ Ideal.span ↑gens
  · constructor
    · exact fun _ => h
    · simp [h]
  · constructor
    · intro ht
      simp [h] at ht
    · exact fun hp => False.elim (h hp)

end Lax619925Proofs.IdealMembership
